name:                nym
version:             0.0.1.0
github:              "khrynczenko/nym"
license:             Apache-2.0
license-file:        LICENSE
author:              "Krzysztof Hrynczenko"
maintainer:          "jeniopy@gmail.com"
copyright:           "2019 Krzysztof Hrynczenko"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/khrynczenko/nym#readme>

dependencies:
- base >= 4.7 && < 5

install-includes:
  - nyms.db

library:
  source-dirs: 
  - src
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Werror
  default-extensions:
  - OverloadedStrings
  dependencies:
  - sqlite-simple
  - text
  - array

executables:
  nym:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -Werror
    default-extensions:
    - OverloadedStrings
    dependencies:
    - nym
    - optparse-applicative
    - text

tests:
  nym-test:
    main:                Spec.hs
    source-dirs:
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -Werror
    default-extensions:
    - OverloadedStrings
    dependencies:
    - nym
    - hspec