name:                nym
version:             0.0.0.0
github:              "khrynczenko/nym"
license:             MIT
author:              "Krzysztof Hrynczenko"
maintainer:          "jeniopy@gmail.com"
copyright:           "2019 Krzysztof Hrynczenko"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/khrynczenko/nym#readme>

dependencies:
- base >= 4.7 && < 5

default-extensions: 
  - OverloadedStrings

library:
  source-dirs: src

executables:
  nym-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nym

tests:
  nym-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    dependencies:
    - nym
    - hspec
